# Generated by Django 6.0.2 on 2026-02-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=20, unique=True, verbose_name='Номер заявки')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('recovery', 'Восстановление'), ('block', 'Блокировка')], max_length=20, verbose_name='Действие')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Причина')),
                ('authority', models.CharField(default='Департамент здравоохранения города Москвы', max_length=100, verbose_name='Орган Исполнительной Власти или учреждение')),
                ('institution', models.CharField(default='ГКБ № 29 им. Н.Э. Баумана', max_length=100, verbose_name='Подведомственное Учреждение')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
                ('department', models.CharField(max_length=200, verbose_name='Отдел')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.CharField(default='г. Москва, Госпитальная площадь, 2', max_length=200, verbose_name='Адрес')),
                ('building', models.CharField(max_length=10, verbose_name='Корпус')),
                ('office', models.CharField(max_length=50, verbose_name='Кабинет')),
                ('current_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Текущая электронная почта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлено на почту')),
            ],
            options={
                'verbose_name': 'Заявка на email',
                'verbose_name_plural': 'Заявки на email',
                'ordering': ['-created_at'],
            },
        ),
    ]
